clusters:
- alias: freshdrop
  data: null
  infra:
    nodes:
    - labels:
        app: postgres
      type: s-1vcpu-3gb
    provider: digital-ocean
    region: nyc1
    version: v1
    volumes:
    - name: postgres
      size: 10
    - name: filestore
      size: 1
    - name: sessionstore
      size: 1
version: v1
